import Head from "next/head";
import Image from "next/image";


export default function About() {
  return (
    <div>
      <Head>
        <title>Fizz Energy | About Us</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fizz-logo.png" />
      </Head>

      <main>

        <div className="about">
            <div className="about__header">
                <div className="bg-video">
                    <video className="bg-video__content" autoPlay muted loop>
                        <source src="AboutVideo-2.mp4" type="video/mp4"/>
                       
                        Your browser is not supported!
                    </video>
              </div>

              <div className="about__title">
                <h2>About Us</h2>
              </div>
            </div>

            <div className="about__content">
                <p>As the Specialist in Energy Management, <span>FIZZ ENERGY SOLUTIONS</span> provides complete photovoltaic solutions for any size installation, from residential rooftops to utility-scale farms. Our innovative products help you get the most efficient solar harvest from your installation, and benefit from having a single supplier for all your components. Our products and solutions are present at every link in the energy chain and contribute to your energy savings.</p>
                <p><span>FIZZ ENERGY SOLUTIONS</span> was established in 2022 to offer tailor-made optimum solutions in the Renewable (Solar) sector. Our Expertise is to provide a complete solution from basic concept to final commissioning of all types of requirements related to Solar sector. We have catered to several organizations in the past and have had a good working relationship with all of them, with no complaints from our clients. As a company, we offer you services that are of the highest standard and at extremely competitive rates.</p>
                <p>Concerning our business service, we are partnered with world-renowned Solar Product Manufacturers.</p>
                <p>For Solar PV Module, we are the sole authorized distributor of Hyundai PV Module. We also offer the TRINA Solar module which is a TIER-1 Brand whereas In Solar Inverters, we have acquired a working partnership with SMA, HUAWEI, and CHINT. Hence we integrate the best possible solar solution with maximum output to our valued Customers. To maintain State of the Art technology, we have also established the after-sales service center in Karachi.</p>
                <p>Fizz Energy had successfully commissioned many Grid-Tie projects up to 1 MW individual capacity and Hybrid Solar Projects all over Pakistan. The performance of such high-quality equipment is well established and renowned. Quality of rest of the material, Installation, Testing and commissioning, all done by the professional and internationally certified Engineers of Fizz Energy ensuring standards of high quality.</p>
            </div>
        </div>
      </main>
    </div>
  );
}

/*
 
<About_us></About_us>
*/
