import Head from "next/head";
import Image from "next/image";


export default function Careers() {
  return (
    <div>
      <Head>
        <title>Fizz Energy | Careers</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fizz-logo.png" />
      </Head>

      <main>

        <div className="careers">

            <div className="careers__top">
                

                <div className="careers__heading_container">
                    <h2 className="careers__heading">Careers</h2>
                </div>

                <div class="custom-shape-divider-bottom-1658044684">
                <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
                    <path d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z" class="shape-fill"></path>
                </svg>
            </div>
            </div>

           


            <div className="careers__category">
                <div className="category__title">
                    <h3>Marketing</h3>
                </div>

                <div className="category__job_card">
                    <div className="job__title">
                        <h6>Area Manager</h6>
                    </div>

                    <div className="job__description">
                        <div className="description__title">
                            <h6>Job Responsibilities</h6>
                        </div>

                        <div className="description">
                            <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet laudantium, veniam ut est exercitationem excepturi corrupti eligendi sit laboriosam ipsa nam illum cum impedit, deserunt, voluptates distinctio alias. Vitae, natus.
                            </p>
                        </div>

                        <div className="apply__email">

                            <h3>To apply for this position please send your updated resume to <span>info@fizzenergies.com</span> </h3>
                        </div>
                    </div>
                </div>

                <div className="category__job_card">
                    <div className="job__title">
                        <h6>Digital Marketing Specialist</h6>
                    </div>

                    <div className="job__description">
                        <div className="description__title">
                            <h6>Job Responsibilities</h6>
                        </div>

                        <div className="description">
                            <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet laudantium, veniam ut est exercitationem excepturi corrupti eligendi sit laboriosam ipsa nam illum cum impedit, deserunt, voluptates distinctio alias. Vitae, natus.
                            </p>
                        </div>

                        <div className="apply__email">

                            <h3>To apply for this position please send your updated resume to <span>info@fizzenergies.com</span> </h3>
                        </div>
                    </div>
                </div>
            </div>

            <div className="careers__category">
                <div className="category__title">
                    <h3>Accounts And Finance</h3>
                </div>

                <div className="category__job_card">
                    <div className="job__title">
                        <h6>Accountant</h6>
                    </div>

                    <div className="job__description">
                        <div className="description__title">
                            <h6>Job Responsibilities</h6>
                        </div>

                        <div className="description">
                            <p>
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet laudantium, veniam ut est exercitationem excepturi corrupti eligendi sit laboriosam ipsa nam illum cum impedit, deserunt, voluptates distinctio alias. Vitae, natus.
                            </p>
                        </div>

                        <div className="apply__email">

                            <h3>To apply for this position please send your updated resume to <span>info@fizzenergies.com</span> </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </main>
    </div>
  );
}

/*
 
<About_us></About_us>
*/
