import Head from "next/head";
import Image from "next/image";

import Header from "../components/Header";
import Benefits from "../components/benefits";
import styles from "../styles/Home.module.scss";
import About_us from "../components/About_us";
import WhyUs from "../components/WhyUs";
import Team from "../components/Team";
import Packages from "../components/Packages";
import Contact_us from "../components/Contact_us";
import Footer from "../components/Footer";
import Social from "../components/Social";
import Chat from "../components/Chat";
import Calculator from "../components/Calculator";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fizz Energy Solutions</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fizz-logo.png" />
      </Head>

      <main className={styles.main}>
        <Social></Social>
        <Chat></Chat>
        <Header></Header>
        <Benefits></Benefits>
        <WhyUs></WhyUs>
        <Packages></Packages>
        <Calculator></Calculator>
        <Team></Team>
        <Contact_us></Contact_us>
      </main>
    </div>
  );
}

/*
 
<About_us></About_us>
*/
